### PR TITLE
Fix long flightpaths

### PR DESCRIPTION
**Pull request by celguar**
New clients don't send full taxi path to server. Trinity Core master uses Dijkstra's Algorithm to find shortest path.
Similar logic is used in this PR. Uses taxi path/node data to calculate distances for each taxi path when proxy starts. Uses this data when user activates long flightpath, also filters uknown taxi nodes.

### CODE REVIEW

**Comment by ratkosrb** [comment]
How are you testing on TrinityCore, when that's for 3.3.5, and Proxy does not support wotlk yet :D

**Comment by celguar** [comment]
I'm not using Trinity Core. I just mean Trinity Core master (Shadowlands) uses Dijkstra's Algorithm to find shortest path to make taxi work, because new clients (classic/tbc too) only send start and end taxi node ID. So I tried to use same approach here

**Comment by celguar** [comment]
I'm saying that because Trinity Core is an open source project so I just opened their Taxi related .cpp files and read comments/code

**Comment by celguar** [comment]
But the only testing I did is on 1.14 and 2.5.2 + proxy + cmangos.

**Comment by celguar** [comment]
I'm sure this could be done in a more elegant way, like make a new class in TaxiHandler and move MinDistance, Dijkstra, SavePath functions in it from GameData. If that is so, please let me know and I'll try to improve it.

**Comment by celguar** [comment]
Moved taxi path functions to Taxi Handler. I saw similar examples in Quest Handler (but for server) having non-packet-handler functions there (ReadExtraQuestInfo) so I did the same. GameData clean now :)

**Pull request merged**
